name: deliverk
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+6

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.0.0
  dio: ^4.0.6
  firebase_core: ^1.21.0
  firebase_messaging: ^12.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launch: ^0.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_local_notifications: ^9.8.0+1
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.0.9
  google_maps_flutter: ^2.1.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_serializable: ^6.3.1
  location: ^4.4.0
  logger: ^1.1.0
  persistent_bottom_nav_bar: ^4.0.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.5
  progress_dialog_null_safe: ^1.0.7

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
