name: deliverk
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^1.1.0
  geolocator: ^9.0.1
  google_maps_flutter: ^2.1.8
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  location: ^4.4.0
  logger: ^1.1.0
  persistent_bottom_nav_bar: ^4.0.2
  provider: ^6.0.3
  syncfusion_flutter_maps: ^20.2.38

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
